services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ../backend:/app
      - ../backend/.env:/app/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../services/Caddyfile:/etc/caddy/Caddyfile
      - ../frontend/dist:/usr/share/caddy        # <-- Montar build frontend aquí
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
